import assert from 'node:assert/strict';
import { demoSprints } from '../collectors/demo.js';
import { scoreSprint, ragFor } from './engine.js';
import { rules } from './sprintRules.js';
import { learnBaseline } from '../cycle.js';
import { peopleStats } from '../people.js';

const all = demoSprints().filter((x) => x.board === 'OSSI');
const s = { ...all[0], baseline: learnBaseline(all) };
const card = scoreSprint(s);
assert.ok(card.score >= 0 && card.score <= 100, 'score in range');
assert.equal(card.findings.length, rules.length, 'every rule produced a finding on demo data');
assert.equal(ragFor(rules[0], 90), 'green');
assert.equal(ragFor(rules[0], 70), 'amber');
assert.equal(ragFor(rules[0], 50), 'red');
const empty = scoreSprint({ ...s, issues: [] });
assert.ok(empty.findings.length < rules.length);
const people = peopleStats(all);
assert.ok(people.length > 0 && people[0].ticketsDone > 0, 'people stats populated');
import { demoGithub } from '../collectors/githubDemo.js';
import { scoreFlow } from './flowRules.js';
import { githubPeople } from '../githubPeople.js';
const g = demoGithub()[0];
const flow = scoreFlow(g);
assert.ok(flow.findings.length >= 10, 'flow rules evaluated');
const gp = githubPeople(g, ['Karim', 'Dinesh']);
assert.ok(gp.find((p) => p.name === 'Karim')?.flags.some((f) => f.startsWith('Reviews only')), 'review-only lead flagged');
assert.ok(gp.find((p) => p.name === 'Dinesh')?.flags.some((f) => f.startsWith('No commits')), 'silent architect flagged');
console.log('rules engine ok');
